#app secret Key
[SecretKey]
SECRET_KEY = gdggjunfdw3434ry6yrtgdfgdbt63e61ifbt56


# Database Credentials
[database]
HOST = nexusfieldservice.axvp7.mongodb.net
USERNAME = Sourav
PASSWORD = l9EG8ULwylphgjHS

[TemplateDB]
DB_NAME = control_panel
COLLECTION_NAME_PRICE= door_model


